blender_exec_path: /home/ola/library/blender283/blender
blender_scene: scene.blend
blender_script: script.py
ground_truth_path: dataset/ground-truth
hdrs_path: dependencies/hdrs
pbrs_path: dependencies/pbrs
stl_corners_path: dependencies/weld-corners-v1
stl_index: 799
stl_path: dependencies/weld-corners-v1/mesh799.stl
train_filt_path: dataset/train-filt
train_raw_path: dataset/train-raw
